pipeline{
    agent any
    tools{nodejs "nod

    stages{
        stage('Install dependencies'){
            steps{
                sh 'npm install'
            }
        }

        stage('Test'){
            steps{
                sh 'npm test'
            }
        }
    }
}